---
driver:
  name: vagrant

provisioner:
  name: nodes

platforms:
- name: windows-2012R2
  driver_config:
    box: mwrock/Windows2012R2Full

suites:
  - name: primary
    driver:
      network:
        - ["private_network", { type: "dhcp" }]
    run_list:
      - recipe[windows_ad_pair::primary]
    attributes:
      windows_ad_pair:
        fqdn: kitchen.local
        options:
          NoRebootOnCompletion: 

  - name: backup
    driver:
      network:
        - ["private_network", { type: "dhcp" }]
    run_list:
      - recipe[windows_ad_pair::backup]
    attributes:
      windows_ad_pair:
        fqdn: kitchen.local
        administrator_password: vagrant
        options:
          NoRebootOnCompletion: 