name             'windows_ad_pair'
maintainer       'Matt Wrock'
maintainer_email 'matt@mattwrock.com'
license          'all_rights'
description      'Installs/Configures windows_ad_pair'
long_description 'Installs/Configures windows_ad_pair'
version          '0.1.0'

depends 'windows'
depends 'ms_dotnet4'
depends 'windows_ad'
